development:
  url: redis://127.0.0.1:6379/0
  namespace: notes_development

test:
  url: redis://127.0.0.1:6379/0
  namespace: notes_test

production:
  url: redis://127.0.0.1:6379/0
  namespace: notes_production
